#! /usr/bin/env python3
# -*- coding: utf-8 -*-

# TODO: change working location to be a temp dir
# TODO: Add option for mkv

import subprocess, os, argparse, datetime, re, sys
from youtube_dl import YoutubeDL
from handleYDL import *

USE_CLI = False
CLI_PATH = 'youtube-dl'


def add_chapters_to_mp4(chapter_file_name:str, name_for_download:str)->None:

    # Use MP4Box to mux the chapter file with the mp4
    subprocess.run(["MP4Box", "-chap", chapter_file_name, name_for_download])

def get_chapters( chapters_str:str )->list:

    # Read the description file
    # Split into time and chapter name

    list_of_chapters = []

    # only increment chapter number on a chapter line
    # chapter lines start with timecode
    line_counter = 1
    for line in chapters_str.split('\n'):
        result = re.search(r"\(?(\d?[:]?\d+[:]\d+)\)?", line)
        try:
            # result = re.search("\(?(\d+[:]\d+[:]\d+)\)?", line)
            time_count = datetime.datetime.strptime(result.group(1), '%H:%M:%S')
        except:
            try:
                # result = re.search("\(?(\d+[:]\d+)\)?", line)
                time_count = datetime.datetime.strptime(result.group(1), '%M:%S')
            except:
                continue
        chap_name = line.replace(result.group(0),"").rstrip(' :\n')
        chap_pos = datetime.datetime.strftime(time_count, '%H:%M:%S')
        list_of_chapters.append((str(line_counter).zfill(2), chap_pos, chap_name))
        line_counter += 1

    return list_of_chapters

def write_chapters_file(chapter_file:str, chapter_list:tuple)->None:

    #open(chapter_file, 'w').close()

    # Write out the chapter file based on simple MP4 format (OGM)
    with open(chapter_file, 'w') as fo:
        for current_chapter in chapter_list:
            fo.write(f'CHAPTER{current_chapter[0]}='
                    f'{current_chapter[1]}\n'
                    f'CHAPTER{current_chapter[0]}NAME='
                    f'{current_chapter[2]}\n')


def split_mp4(chapters:list, download_filename:str, download_name:str)->None:

    # current_duration = subprocess.run(['ffprobe', '-i', download_filename,
                                       # '-show_entries', 'format=duration',
                                       # '-v', 'quiet', '-of', 'csv="p=0"'],
                                        # capture_output=True, encoding='UTF8')
    current_duration_pretext = subprocess.run(['ffprobe', '-i', download_filename,
                                       '-show_entries', 'format=duration',
                                       '-v', 'quiet'],
                                        capture_output=True, encoding='UTF8')
    current_duration = float(current_duration_pretext.stdout[18:-13])
    m, s = divmod(current_duration, 60)
    h, m = divmod(m, 60)
    current_dur = ':'.join([str(int(h)),str(int(m)),str(s)])
    for current_index, current_chapter in enumerate(chapters):
        # current_chapter will be a tuple: position, timecode, name
        next_index = current_index + 1
        start_time = current_chapter[1]
        try:
            end_time = chapters[next_index][1]
        except:
            end_time = current_dur
        output_name = f'{download_name} - ({current_chapter[2]}).mp4'
        subprocess.run(["ffmpeg", "-ss", start_time, "-to", end_time,
                        "-i", download_filename, "-acodec", "copy",
                        "-vcodec", "copy", output_name])

def get_args():
    parser = argparse.ArgumentParser(description='Download Youtube videos with chapters')

    parser.add_argument('links', metavar='N', type=str, nargs='+',
                        help='List of links to download')
    
    parser.add_argument("-d", "--descriptions", metavar='D', type=str, nargs='+', 
                        help="Define a file to get the chapter's timestamps")
    parser.add_argument("--split", help="Split chapters into individual files",
                        action="store_true")
    parser.add_argument("--test", help="Download worst version to speed up testing",
                        action="store_true")
    parser.add_argument("--fix", help="Pause to allow manual correction of the description file",
                        action="store_true")
    
    return parser.parse_args()

if __name__ == '__main__':

    args = get_args()
    
    for index in range( 0, len(args.links) ):
        
        link_to_download = args.links[index]
        options = {}
        
        options['outtmpl'] = '%(title)s'
        infos = get_infos( link_to_download, options )
        
        download_name = infos['title']
        download_filename = f'{download_name}.mp4'
        chapter_file = f'{download_name}_chapter.txt'
        description = infos['description']
        
        print(download_name)
        print(download_filename)

        if args.fix:
            input("Fix the description file to have the chapters "
                  "on their own lines in the format timecode name "
                  "and then press Enter to continue...")
        
        chapters = get_chapters( description )

        if not args.test:
            options['format'] = "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4"
        else:
            options['format'] = "worstvideo[ext=mp4]+worstaudio[ext=m4a]/mp4"
        download( link_to_download, options )
        
        if not chapter_file:
            print("No chapters found")
            sys.exit(1)
        
        write_chapters_file(chapter_file=chapter_file, chapter_list=chapters)

        if args.split:
            split_mp4(chapters=chapters, download_filename=download_filename,
                      download_name=download_name)
        
        add_chapters_to_mp4(chapter_file_name=chapter_file,
                              name_for_download=download_filename)

        # Clean up the text files
        os.remove(chapter_file)
